use_frameworks!

platform :ios, '8.0'

target 'CTLTrackingAds-SDK_Example' do
  pod 'CTLTrackingAds-SDK', :path => '../'

  target 'CTLTrackingAds-SDK_Tests' do
    inherit! :search_paths

    
  end
end
